// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	github "ai-code-reviewer/internal/github"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommentClient is an autogenerated mock type for the CommentClient type
type CommentClient struct {
	mock.Mock
}

type CommentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentClient) EXPECT() *CommentClient_Expecter {
	return &CommentClient_Expecter{mock: &_m.Mock}
}

// CreateLineComment provides a mock function with given fields: ctx, repo, pr, comment
func (_m *CommentClient) CreateLineComment(ctx context.Context, repo string, pr int, comment github.LineComment) error {
	ret := _m.Called(ctx, repo, pr, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateLineComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, github.LineComment) error); ok {
		r0 = rf(ctx, repo, pr, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommentClient_CreateLineComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLineComment'
type CommentClient_CreateLineComment_Call struct {
	*mock.Call
}

// CreateLineComment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - pr int
//   - comment github.LineComment
func (_e *CommentClient_Expecter) CreateLineComment(ctx interface{}, repo interface{}, pr interface{}, comment interface{}) *CommentClient_CreateLineComment_Call {
	return &CommentClient_CreateLineComment_Call{Call: _e.mock.On("CreateLineComment", ctx, repo, pr, comment)}
}

func (_c *CommentClient_CreateLineComment_Call) Run(run func(ctx context.Context, repo string, pr int, comment github.LineComment)) *CommentClient_CreateLineComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(github.LineComment))
	})
	return _c
}

func (_c *CommentClient_CreateLineComment_Call) Return(_a0 error) *CommentClient_CreateLineComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CommentClient_CreateLineComment_Call) RunAndReturn(run func(context.Context, string, int, github.LineComment) error) *CommentClient_CreateLineComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommentClient creates a new instance of CommentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentClient {
	mock := &CommentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
