// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ai "ai-code-reviewer/internal/ai"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// Review provides a mock function with given fields: ctx, r
func (_m *Provider) Review(ctx context.Context, r ai.ReviewRequest) (ai.ReviewResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Review")
	}

	var r0 ai.ReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ai.ReviewRequest) (ai.ReviewResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ai.ReviewRequest) ai.ReviewResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(ai.ReviewResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ai.ReviewRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_Review_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Review'
type Provider_Review_Call struct {
	*mock.Call
}

// Review is a helper method to define mock.On call
//   - ctx context.Context
//   - r ai.ReviewRequest
func (_e *Provider_Expecter) Review(ctx interface{}, r interface{}) *Provider_Review_Call {
	return &Provider_Review_Call{Call: _e.mock.On("Review", ctx, r)}
}

func (_c *Provider_Review_Call) Run(run func(ctx context.Context, r ai.ReviewRequest)) *Provider_Review_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ai.ReviewRequest))
	})
	return _c
}

func (_c *Provider_Review_Call) Return(_a0 ai.ReviewResponse, _a1 error) *Provider_Review_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_Review_Call) RunAndReturn(run func(context.Context, ai.ReviewRequest) (ai.ReviewResponse, error)) *Provider_Review_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
